name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Terraform
    concurrency:
      group: infrastructure
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Image
        run: |
          az acr login --name acrjournalapp
          docker build --platform linux/amd64 -t acrjournalapp.azurecr.io/journal_app:latest .
          docker push acrjournalapp.azurecr.io/journal_app:latest

      - name: Restart Web App
        run: az webapp restart --name $(az webapp list --query "[?contains(name, 'app-journalapp')].name" -o tsv) --resource-group rg-journal-app
